### ISSUE TITLE
Deconstruction Planner 

### ISSUE THREAD

**Issue by Soundra-1** [dustine/ChargeTransmission#1]
When you use a Deconstruction Planner only the "Bot Charger Kevin Leonhard Haugen NOR" is removed. The "Boot Charger Transmitter" is left. The game gives this error:

LuaEntriry API call when LuaEntity was invalid. stack traceback: __ChargeTransmission__/stdlib/entity /entity.lua:44 in function 'get_data' __ChargeTrasmission_control.lua:286 in function <__ChargeTransmission__/Control.lua:281> [C]:in function 'pccall' __ChargeTransmission__/stdlib/entity /entity.lua:99 in function <__ChargeTransmission__/stdlib/event/event.lua:82>

If I use Deconstruction Planner on several the game crashes.

**Comment by dustine** [comment]
Heyo! Before anything, thank you so much for the bug report. My first official one 🎉

I've been unable to replicate the bug when using the vanilla deconstructor:
![image](https://user-images.githubusercontent.com/8994495/31310977-69bd0126-ab9a-11e7-93d4-1fa9a8f80035.png)

But using it under Creative Mode's instant deconstruction does lead to the bug you reported (the faulty deconstruction, haven't managed to get the game to crash yet). I'll see if I can fix it for that scenario, but meanwhile I'd like to make sure if you were using any other mods when you attempted to deconstruct the chargers.

**Edit:** Got the game to crash, still under Creative Mode's instant deconstruction.

**Comment by dustine** [comment]
Found the cause which caused it to fail with several mods that did custom deconstructions (Creative Mode, Nanobots potentially, ...). The fix is generic enough that it should solve this case, whenever the source. Please reply here if it hasn't, and sorry for the additional hassle.

**Comment by Soundra-1** [comment]
Thank you for the quick response. Yes I was using "creative-mode" to make blue prints. Updated and its working wonderfully. 
Thanks the mod.
