### ISSUE TITLE
0.16 isn't supported

### ISSUE THREAD

**Issue by dewitpj** [dustine/ChargeTransmission#3]
The mod is incompatible with 0.16 :(

**Comment by dustine** [comment]
Yeah, sorry about that. The mod is in the middle of a rewrite and I was hoping I would have it finished for 0.16, but I didn't manage it. That and I've been busy with another mod too, which hasn't helped me -u-

I will do a quick port to 0.16 if not in a few hours, tomorrow.

**Comment by dewitpj** [comment]
Confirm the update is loaded into the portal as well.

Thanks !
